//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZadohinControl10.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DepoZadohinEntities : DbContext
    {
        public DepoZadohinEntities()
            : base("name=DepoZadohinEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<FloorFlight> FloorFlight { get; set; }
        public DbSet<sysdiagrams> sysdiagrams { get; set; }
        public DbSet<Train> Train { get; set; }
        public DbSet<Ucet> Ucet { get; set; }
        public DbSet<VidWork> VidWork { get; set; }
        public DbSet<Work> Work { get; set; }
    }
}
