//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZadohinControl10.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class FloorFlight
    {
        public FloorFlight()
        {
            this.Train = new HashSet<Train>();
        }
    
        public int id { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<Train> Train { get; set; }
    }
}
