//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZadohinControl10.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ucet
    {
        public int id { get; set; }
        public Nullable<System.DateTime> DateWork { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<int> idTrain { get; set; }
        public Nullable<int> idWork { get; set; }
    
        public virtual Train Train { get; set; }
        public virtual Work Work { get; set; }
    }
}
